### PR TITLE
Tina/summaryVisuals new icons and grid layout in Summary.

### PR DESCRIPTION
**Pull request by QueenChristina**
Updated summary visuals to match Figma design: new driving, water, and land icons with grid layout.

[Minor] Also looked into having scrollbar show up on IOS mobile: 
https://stackoverflow.com/questions/22907777/make-scrollbar-visible-in-mobile-browsers
https://stackoverflow.com/questions/3512885/how-do-i-get-scrollbars-to-show-in-mobile-safari
https://stackoverflow.com/questions/14842876/how-to-force-a-scroll-bar-to-appear-in-the-ipad-mobile-safari 
This will need testing to see effectiveness -- if this doesn't work, we may need separate library to rebuilt scrollbars.

### CODE REVIEW

**Comment by tonychen2** [comment]
I hope Jenny is not going to fight me for this, but I feel like the information density here is a bit low on desktop (too much white space). 
image Can we reduce the margin slightly? @jennywjs @jeffkassab

**Comment by tonychen2** [comment]
@QueenChristina talked to Jeff and Jenny and they agree. Can we adjust the margin, please?

**Comment by QueenChristina** [comment]
> @QueenChristina talked to Jeff and Jenny and they agree. Can we adjust the margin, please?

By how much are we adjusting the margin? You're free to adjust it as well if you think that's faster.

**Comment by QueenChristina** [comment]
image

I've adjusted the margins. Feel free to adjust further if it still feels off.

**Review by tonychen2 — APPROVED** [review]

**Pull request merged**
