### PR TITLE
Tony/logos

### PR DESCRIPTION
**Pull request by tonychen2**
Three minor changes:
1. Added favicon
2. Enabled users to clear grocery list by clicking on our logo in the header
3. Some information on the Google Analytics setup in README

### CODE REVIEW

**Review by QueenChristina — APPROVED** [review]
Looks good. Amazing refreshing the page is so simple -- so much more elegant than my solution of clearing only the grocery list component, which you can see on 'tina/feedback' branch.

But your solution does refresh the whole page instead of just clearing the grocery list, which may or may not be intended behavior (since refreshing is slower, the user can see the visual effect of refreshing the page; but it is nice that it resets the whole page).

Perhaps we can discuss the exact intended behavior of clicking the logo sometime in the future?

**Comment by tonychen2** [comment]
I'm not too worried about it. If you want you can bring it up with Jenny
and see what she thinks!

**Comment by QueenChristina** [comment]
Ok, since it's not a big deal and since there's a separate refresh button quite close to the logo already built into the browser, I'll just take the liberty to decide that intended behavior is to only clear the grocery list and not refresh the page.

We can reevaluate in the future if need be.

**Comment by tonychen2** [comment]
Sure! Except then you just need to revert my changes haha since it's your
call.

**Pull request merged**
